-- Optional verification after commissions.sql. Test records roll back.
begin;
do $$
declare adm uuid:=gen_random_uuid(); amb uuid:=gen_random_uuid(); other_amb uuid:=gen_random_uuid(); p uuid; c uuid; stamp timestamptz; commission_stamp timestamptz; visible integer; denied boolean;
begin
 insert into auth.users(id,email) values(adm,adm::text||'@commission-test.invalid'),(amb,amb::text||'@commission-test.invalid'),(other_amb,other_amb::text||'@commission-test.invalid');
 update public.portal_profiles set active=true where id in(adm,amb,other_amb);
 update public.portal_profiles set role='admin' where id=adm;
 perform set_config('request.jwt.claim.sub',adm::text,true);
 perform set_config('request.jwt.claims',json_build_object('sub',adm,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 p:=public.portal_save_project(null,null,'Test client','Website','',null,'not_started',150000,0,'','');
 c:=public.portal_save_commission(p,amb,10000,false,0,'',null);
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',amb::text,true);
 execute 'set local role authenticated';
 select count(*) into visible from public.portal_commissions where id=c;
 if visible<>0 then raise exception 'FAIL: unapproved commission visible.'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',adm::text,true);
 execute 'set local role authenticated';
 select updated_at into commission_stamp from public.portal_commissions where id=c;
 perform public.portal_save_commission(p,amb,10000,true,0,'',commission_stamp);
 select updated_at into stamp from public.portal_projects where id=p;
 perform public.portal_save_project(p,stamp,'Test client','Website','',null,'in_progress',150000,90000,'Deposit confirmed','');
 if (select eligible_amount from public.portal_commissions where id=c)<>5000 then raise exception 'FAIL: deposit did not unlock half.'; end if;
 select updated_at into commission_stamp from public.portal_commissions where id=c;
 denied:=false;
 begin perform public.portal_save_commission(p,amb,10000,true,5500,'Transfer test',commission_stamp); exception when others then if sqlerrm='Confirmed commission payments must be within the eligible amount.' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL: ineligible payout recorded.'; end if;
 perform public.portal_save_commission(p,amb,10000,true,5000,'Confirmed transfer reference TEST-1',commission_stamp);
 select updated_at into stamp from public.portal_projects where id=p;
 denied:=false;
 begin perform public.portal_save_project(p,stamp,'Test client','Website','',null,'in_progress',150000,0,'',''); exception when others then if sqlerrm='Project payments cannot change in a way that invalidates paid commission.' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL: paid commission invalidated.'; end if;
 perform public.portal_save_project(p,stamp,'Test client','Website','',null,'completed',150000,150000,'Fully paid','');
 if (select eligible_amount from public.portal_commissions where id=c)<>10000 then raise exception 'FAIL: full payment did not unlock remainder.'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',amb::text,true);
 execute 'set local role authenticated';
 select count(*) into visible from public.portal_commissions where id=c;
 if visible<>1 then raise exception 'FAIL: owner cannot see approved commission.'; end if;
 denied:=false;
 begin perform public.portal_save_commission(p,amb,10000,true,10000,'Self payout',null); exception when others then if sqlerrm='Admin access required.' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL: ambassador recorded payout.'; end if;
 denied:=false;
 begin update public.portal_commissions set paid_amount=10000 where id=c; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'FAIL: direct commission edit allowed.'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',other_amb::text,true);
 execute 'set local role authenticated';
 select count(*) into visible from public.portal_commissions where id=c;
 if visible<>0 then raise exception 'FAIL: another ambassador read commission.'; end if;
 execute 'reset role';
 raise notice 'PASS: approval, half/full eligibility, payout bounds, paid-payment protection and ambassador isolation.';
end $$;
rollback;
