import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {stageLabels,nextStage,canInvite,onboardingArgs,onboardingFollowupArgs,followupLabel} from '../onboarding-core.mjs';
const source=readFileSync(new URL('../onboarding.js',import.meta.url),'utf8').replace(/^import[^\n]+\n/,'').replace('export function','function');
function fixture(){
 class Node {constructor(){this.children=[];this.value='';this.open=false;this.hidden=false;this.disabled=false;this.textContent='';}append(...v){this.children.push(...v)}replaceChildren(...v){this.children=v}addEventListener(){}showModal(){this.open=true}close(){this.open=false}querySelectorAll(){return Object.entries(nodes).filter(([k])=>/close|invite|save|link$|refresh|letter/.test(k)).map(([,v])=>v)}}
 const nodes={};for(const id of new Set([...source.matchAll(/\$\('#([^']+)'\)/g)].map(m=>m[1])))nodes['#'+id]=new Node();
 let detail={application:{id:'app',status:'accepted',email:'test@example.com',full_name:'Test'},letter_reference:'letter',member_id:null,member:null,candidates:[],notes:'',revision:0,followup_date:null,today:'2026-10-11'};
 const calls=[];let failure=null,recheck=null;
 const api={async rpc(name,args){calls.push([name,args]);if(name==='mua_onboarding_detail'){if(recheck&&calls.filter(c=>c[0]===name).length===2)recheck(detail);return structuredClone(detail)}if(name==='mua_onboarding_list')return {rows:[],accepted:1,letter:0,invite:1,signin:0,ready:0,paused:0};if(name==='mua_save_onboarding_followup'){detail.followup_date=args.p_followup_date;detail.member_id=args.p_member_id;detail.member={email:'test@example.com',active:true};detail.revision++;}},async invite(email,name){calls.push(['invite',email,name]);if(failure)throw new Error(failure);detail.candidates=[{id:'member',email,full_name:name,active:true}];}};
 const document={querySelector:s=>nodes[s],createElement:()=>new Node()};
 const create=vm.runInNewContext(source+';createOnboarding',{document,window:{confirm:()=>true},Option:class extends Node{constructor(label,value){super();this.textContent=label;this.value=value}},stageLabels,nextStage,canInvite,onboardingArgs,onboardingFollowupArgs,followupLabel,setTimeout,clearTimeout});
 return {nodes,calls,detail,controller:create(api,{open(){}}),setFailure(v){failure=v},setRecheck(v){recheck=v}};
}
test('Confirmed invitation is rechecked and linked after success, not treated as ready',async()=>{const f=fixture();await f.controller.open('app');await f.nodes['#onboarding-invite'].onclick();assert.equal(f.calls.filter(c=>c[0]==='invite').length,1);assert.equal(f.detail.member_id,'member');assert.match(f.nodes['#onboarding-message'].textContent,/Delivery is not confirmed/);assert.equal(f.nodes['#onboarding-stage'].textContent,'Awaiting portal sign-in');});
test('Double clicks do not send concurrent invitations',async()=>{const f=fixture();await f.controller.open('app');await Promise.all([f.nodes['#onboarding-invite'].onclick(),f.nodes['#onboarding-invite'].onclick()]);assert.equal(f.calls.filter(c=>c[0]==='invite').length,1);});
test('Existing account is linked without email',async()=>{const f=fixture();f.detail.candidates=[{id:'member',email:'test@example.com',active:false}];await f.controller.open('app');assert.equal(f.nodes['#onboarding-invite'].hidden,true);f.nodes['#onboarding-account'].value='member';f.nodes['#onboarding-link'].onclick();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(f.calls.filter(c=>c[0]==='invite').length,0);assert.equal(f.detail.member_id,'member');});
test('Changed acceptance prevents a stale invitation',async()=>{const f=fixture();f.setRecheck(d=>{d.application.status='declined'});await f.controller.open('app');await f.nodes['#onboarding-invite'].onclick();assert.equal(f.calls.filter(c=>c[0]==='invite').length,0);assert.match(f.nodes['#onboarding-message'].textContent,/changed/);});
test('Invitation failure retains notes and does not retry automatically',async()=>{const f=fixture();f.setFailure('Network failure');await f.controller.open('app');f.nodes['#onboarding-notes'].value='Follow up';await f.nodes['#onboarding-invite'].onclick();assert.equal(f.calls.filter(c=>c[0]==='invite').length,1);assert.equal(f.calls.filter(c=>c[0]==='mua_save_onboarding_followup').length,0);assert.equal(f.nodes['#onboarding-notes'].value,'Follow up');assert.match(f.nodes['#onboarding-message'].textContent,/Do not repeatedly resend/);assert.equal(f.nodes['#onboarding-invite'].disabled,false);});
test('Clearing cancels in-flight detail rendering',async()=>{const f=fixture();const pending=f.controller.open('app');f.controller.clear();await pending;assert.equal(f.nodes['#onboarding-dialog'].open,false);assert.equal(f.nodes['#onboarding-checks'].children.length,0);});
test('Follow-up date and notes are saved together',async()=>{const f=fixture();await f.controller.open('app');f.nodes['#onboarding-followup'].value='2026-10-11';f.nodes['#onboarding-notes'].value='Call applicant';await f.nodes['#onboarding-save'].onclick();const call=f.calls.find(c=>c[0]==='mua_save_onboarding_followup');assert.equal(call[1].p_followup_date,'2026-10-11');assert.equal(call[1].p_notes,'Call applicant');assert.match(f.nodes['#onboarding-followup-status'].textContent,/Due today/);});
test('Invalid date prevents invitation before an email request',async()=>{const f=fixture();await f.controller.open('app');f.nodes['#onboarding-followup'].value='2026-02-30';await f.nodes['#onboarding-invite'].onclick();assert.equal(f.calls.filter(c=>c[0]==='invite').length,0);assert.match(f.nodes['#onboarding-message'].textContent,/valid follow-up date/);});
test('A concurrent notes revision prevents stale invitation actions',async()=>{const f=fixture();f.setRecheck(d=>{d.revision++});await f.controller.open('app');await f.nodes['#onboarding-invite'].onclick();assert.equal(f.calls.filter(c=>c[0]==='invite').length,0);});
