import {createOnboarding} from './onboarding.js?v=20261011-followups';
import {PortalAPI} from './api.js';
import {createAppointments} from './appointments.js?v=20261010';
import {statuses,reviewArgs,applicationQuery} from './applications-core.mjs';
const embedded=window.self!==window.top&&new URLSearchParams(location.search).get('embedded')==='1';
if(embedded)document.body.classList.add('embedded-review');
const api=new PortalAPI(window.MUA_PORTAL_CONFIG||{}), $=s=>document.querySelector(s);
const appointments=createAppointments(api);
const onboarding=createOnboarding(api,appointments);
let onboardingView=false;
function switchView(value){onboardingView=value;$('#application-results').hidden=value;$('#onboarding-view').hidden=!value;$('#applications-tab').setAttribute('aria-pressed',String(!value));$('#onboarding-tab').setAttribute('aria-pressed',String(value));if(value)onboarding.load();}
$('#applications-tab').onclick=()=>switchView(false);
$('#onboarding-tab').onclick=()=>switchView(true);
let page=0,current=null,request=0,detailRequest=0;
const date=v=>v?new Date(v).toLocaleString('en-NG',{timeZone:'Africa/Lagos',dateStyle:'medium',timeStyle:'short'}):'Not reviewed';
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function badge(status){return el('span',status.charAt(0).toUpperCase()+status.slice(1),'badge '+status)}
function message(text){$('#message').textContent=text;}
async function access(){const profile=await api.profile();if(!profile||profile.role!=='admin'||!profile.active)throw new Error('An active MUA administrator account is required.');$('#identity').textContent=profile.full_name+' · Administrator';$('#gate').hidden=true;$('#review').hidden=false;}
async function stats(){const values=await api.rpc('mua_application_review_summary',{});$('#stats').replaceChildren(...statuses.map(status=>{const n=el('div',undefined,'stat');n.append(el('strong',values[status]??0),el('span',status.charAt(0).toUpperCase()+status.slice(1)));return n}));const selected=$('#state').value;$('#state').replaceChildren(new Option('All states',''),...(values.states||[]).map(s=>new Option(s,s)));$('#state').value=selected;}

async function load(){const ticket=++request;message('Loading applications…');$('#list').replaceChildren();$('#previous').disabled=true;$('#next').disabled=true;try{await access();const rows=await api.request(applicationQuery({search:$('#search').value,status:$('#status').value,state:$('#state').value,page}));if(ticket!==request)return;const visible=rows.slice(0,12);$('#list').replaceChildren(...visible.map(row=>{const card=el('article',undefined,'card');card.append(badge(row.status),el('h2',row.full_name),el('p',row.reference),el('p',row.state+' · '+row.city),el('p',row.qualification),el('p',row.email),el('p','Submitted '+date(row.created_at)));const b=el('button','Review application');b.addEventListener('click',()=>open(row.id));card.append(b);return card}));$('#count').textContent=visible.length?`${visible.length} applications on this page`:'No applications match this view.';$('#page').textContent='Page '+(page+1);$('#previous').disabled=page===0;$('#next').disabled=rows.length>12?false:true;message('');}catch(e){if(ticket===request)message(e.message);}}
async function open(id){const ticket=++detailRequest;current=null;$('#save').disabled=true;$('#appointment-open').hidden=true;$('#applicant').textContent='Loading…';$('#brief').replaceChildren();$('#history').replaceChildren();$('#decision-message').textContent='';if(!$('#detail').open)$('#detail').showModal();try{await access();const [rows,history]=await Promise.all([api.request('/rest/v1/mua_ambassador_applications?id=eq.'+encodeURIComponent(id)+'&select=*'),api.request('/rest/v1/mua_application_reviews?application_id=eq.'+encodeURIComponent(id)+'&select=*&order=created_at.desc,id.desc&limit=100')]);if(ticket!==detailRequest||!$('#detail').open)return;if(!rows[0])throw new Error('Application unavailable.');current=rows[0];$('#appointment-open').hidden=current.status!=='accepted';$('#applicant').textContent=current.full_name;const fields={reference:'Reference',email:'Email',phone:'Phone',state:'State',city:'City',occupation:'Occupation',qualification:'Highest qualification',availability:'Time available',audiences:'Outreach groups',profile_url:'Profile link',motivation:'Motivation',experience:'Experience',outreach_plan:'Outreach plan',created_at:'Submitted (Nigerian time)',reviewed_at:'Last reviewed (Nigerian time)'};for(const [key,label]of Object.entries(fields)){$('#brief').append(el('dt',label),el('dd',key.endsWith('_at')?date(current[key]):Array.isArray(current[key])?current[key].join(', '):current[key]||'Not provided'));}$('#decision').elements.status.value=current.status;$('#decision').elements.notes.value=current.review_notes||'';$('#history').replaceChildren(...history.map(h=>el('p',`${date(h.created_at)}\n${h.old_status} → ${h.new_status}\n${h.notes||'No notes'}\nReviewer ID: ${h.actor_id}`,'history-item')));if(!history.length)$('#history').append(el('p','No review decisions yet.'));$('#save').disabled=false;}catch(e){$('#decision-message').textContent=e.message;}}
$('#decision').addEventListener('submit',async e=>{e.preventDefault();if(!current)return;const row=current;$('#save').disabled=true;$('#close').disabled=true;try{await api.rpc('mua_review_application',reviewArgs(row,$('#decision').elements.status.value,$('#decision').elements.notes.value));$('#detail').close();current=null;await Promise.all([load(),stats()]);message('Review saved.');}catch(e){$('#decision-message').textContent=e.message;}finally{$('#save').disabled=false;$('#close').disabled=false;}});
$('#appointment-open').onclick=()=>{if(current)appointments.open(current)};
$('#close').onclick=()=>{$('#detail').close();detailRequest++;current=null};
$('#detail').addEventListener('cancel',e=>{if($('#close').disabled)e.preventDefault();else{detailRequest++;current=null}});
$('#login').onsubmit=async e=>{e.preventDefault();const b=$('#login button');b.disabled=true;try{await api.signIn(e.target.elements.email.value,e.target.elements.password.value);await access();await Promise.all([load(),stats()]);e.target.reset();}catch(e){message(e.message)}finally{b.disabled=false}};
$('#signout').onclick=async()=>{appointments.clear();onboarding.clear();try{await api.signOut()}catch{}request++;detailRequest++;current=null;$('#detail').close();$('#list').replaceChildren();$('#brief').replaceChildren();$('#history').replaceChildren();$('#review').hidden=true;$('#gate').hidden=false;message('Signed out.');if(embedded)window.parent.postMessage({type:'mua-review-signout'},location.origin);};
let timer;$('#search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{page=0;load()},300)};for(const s of ['#status','#state'])$(s).onchange=()=>{page=0;load()};$('#previous').onclick=()=>{page--;load()};$('#next').onclick=()=>{page++;load()};$('#refresh').onclick=()=>onboardingView?onboarding.load():Promise.all([load(),stats()]).catch(e=>message(e.message));
if(api.session)(async()=>{try{await access();await Promise.all([load(),stats()])}catch(e){message(e.message)}})();
